# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

language: python
sudo: false

python:
- 2.7
- 3.4
- 3.5

before_install:
    - export WHEELHOUSE="--no-index --find-links=http://wheels.scikit-image.org/"
    - pip uninstall -y numpy
    - pip install $WHEELHOUSE numpy
    - pip install -U pip

script:
    - make test
